name: track_mauzo
description: TrackMauzo - Your Ultimate Business Tracking Solution
publish_to: "none"
version: 1.0.0+1

environment:
  flutter: ">=3.35.0 <3.36.0"
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  image_picker: ^1.2.2
  http: ^1.2.2
  pdf: ^3.12.0
  path_provider: ^2.1.5
  printing: ^5.14.3
  url_launcher: ^6.3.2
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.20.2
  google_mlkit_text_recognition: ^0.13.0
  speech_to_text: ^7.0.0
  share_plus: ^13.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # code style
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
